"use client";

import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { z } from "zod";
import { IconDatabaseSearch, IconSend, IconShieldLock } from "@tabler/icons-react";
import { engine } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";

const schema = z.string().trim().min(3).max(1000);

export function IntelligenceClient() {
  const [answer, setAnswer] = useState<{ text: string; contextCount: number } | null>(null);
  const me = useQuery({ queryKey: ["me"], queryFn: engine.me });
  const ask = useMutation({ mutationFn: engine.ask, onSuccess: (result) => setAnswer({ text: result.answer, contextCount: result.contextCount }), onError: (error: Error) => toast.error(error.message) });

  function submit(formData: FormData) {
    const parsed = schema.safeParse(formData.get("query"));
    if (!parsed.success) return toast.error("Enter a clear intelligence question.");
    setAnswer(null);
    ask.mutate(parsed.data);
  }

  return (
    <div className="page-shell max-w-6xl">
      <div className="page-header"><div><p className="page-eyebrow">Organization knowledge</p><h1 className="page-title">Ask Intelligence</h1><p className="page-description">Query completed investigation knowledge indexed for your organization. Answers are constrained to retrieved evidence and are generated by Cloudflare Workers AI.</p></div></div>
      <div className="grid gap-3 lg:grid-cols-[minmax(0,1fr)_300px]">
        <Card>
          <CardHeader><div><p className="page-eyebrow">Evidence query</p><CardTitle>Investigation knowledge</CardTitle></div><IconDatabaseSearch className="text-muted-foreground" size={17} /></CardHeader>
          <CardContent>
            <form action={submit} className="space-y-3"><Textarea name="query" maxLength={1000} placeholder="Example: Which domains or email addresses appeared across our recent completed investigations, and which findings were assessed as high risk?" required /><div className="flex items-center justify-between gap-3"><span className="text-[11px] text-muted-foreground">No general-web answering. Retrieved organization evidence only.</span><Button type="submit" disabled={ask.isPending || me.data?.plan === "free"}>{ask.isPending ? "Searching…" : "Ask Intelligence"}<IconSend /></Button></div></form>
            <div className="mt-5 min-h-[260px] rounded-md border border-border bg-background p-4">
              {ask.isPending && <div className="flex items-center gap-2 text-sm text-muted-foreground"><span className="size-2 animate-pulse rounded-full bg-foreground" /> Retrieving indexed investigation context…</div>}
              {!ask.isPending && !answer && <div className="grid min-h-[220px] place-items-center text-center"><div><IconShieldLock className="mx-auto mb-3 text-muted-foreground" size={24} /><p className="m-0 text-sm font-medium">Grounded intelligence only</p><p className="mx-auto mt-2 max-w-md text-[11px] leading-5 text-muted-foreground">The assistant is instructed not to invent exposures, threat actors, credentials, dates or indicators when indexed context does not support them.</p></div></div>}
              {answer && <div><div className="mb-4 flex items-center justify-between gap-3 border-b border-border pb-3"><span className="page-eyebrow !mb-0">Grounded answer</span><span className="font-mono text-[10px] text-muted-foreground">{answer.contextCount} CONTEXT CHUNKS</span></div><div className="whitespace-pre-wrap text-[13px] leading-6 text-foreground/90">{answer.text}</div></div>}
            </div>
          </CardContent>
        </Card>
        <Card className="h-fit"><CardHeader><div><p className="page-eyebrow">Access</p><CardTitle>{me.data?.plan?.toUpperCase() ?? "—"}</CardTitle></div></CardHeader><CardContent className="space-y-3 text-[11px] leading-5 text-muted-foreground"><p className="m-0">AI Search is a paid-plan capability in the intelligence engine.</p><p className="m-0">The dashboard does not send prompts to OpenAI, Google Gemini or Anthropic.</p>{me.data?.plan === "free" && <p className="m-0 text-amber-300">Upgrade is required before organization knowledge search can run.</p>}</CardContent></Card>
      </div>
    </div>
  );
}
